services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/logs/nginx/
    ports:
      - ${NGINX_PORT:-8888}:80

  test:
    image: mendhak/http-https-echo:25
    ports:
      - 8443
      - 8080
